### ISSUE TITLE
Task list milestone 1

### ISSUE THREAD

**Issue by sreejithmunthikodu** [UBC-MDS/Kmeans_python#1]
- [x] Choose a project
- [x] Create a project structure for Python project
- [x] Create issues for each function, assign and label, add to project board. Write empty functions and docstring
- [x] Create teamwork document
- [x] Create CONTRIBUTORS.md
- [x] Create CONDUC.md
- [x] Create CONTRIBUTING.md
- [x] Create Readme.md
