### ISSUE TITLE
To-do list for milestone 3

### ISSUE THREAD

**Issue by saurav193** [UBC-MDS/Kmeans_python#50]
- [x] Update README with usages

- [x] Create YAML file for build

- [x] Publish R package

- [x] Publish python package

**Comment by RobBlumberg** [comment]
all taks complete, closing
